# Generated by Django 4.2.5 on 2023-10-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
