# Generated by Django 4.2.5 on 2023-10-20 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalcost', models.IntegerField()),
                ('customerobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiceapp.form')),
                ('productobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiceapp.product')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
