# Generated by Django 4.2.5 on 2023-10-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customerobj',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='productobj',
            new_name='product',
        ),
    ]
