# Generated by Django 4.2.5 on 2023-11-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0005_rename_form_user_payment_orders_order_pet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.IntegerField(),
        ),
    ]
